name: Deploy To GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: my-cluster
  GKE_REGION: us-central1
  DEPLOYMENT_NAME: mlops-app
  IMAGE: us-central1-docker.pkg.dev/elections-471503/my-repo/mlops-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    container:
         image: google/cloud-sdk:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GCloud
        run: |
          gcloud config set project "$PROJECT_ID"
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t "$IMAGE:$GITHUB_SHA" .
          docker tag "$IMAGE:$GITHUB_SHA" "$IMAGE:latest"

      - name: Push Docker image
        run: |
          docker push "$IMAGE:$GITHUB_SHA"
          docker push "$IMAGE:latest"
      
      - name: GKE Configuration
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION" --project $"PROJECT_ID"
           

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes-deploy.yaml
          kubectl set image deployment/"$DEPLOYMENT_NAME" "$DEPLOYMENT_NAME"="$IMAGE:$GITHUB_SHA"
          kubectl rollout status deployment/"$DEPLOYMENT_NAME"
